### ISSUE TITLE
2 rendered strips menus exist, looks a bit ugly

### ISSUE THREAD

**Issue by Craanky** [tin2tin/add_rendered_strips#1]
![Screenshot from 2023-09-11 19-45-51](https://github.com/tin2tin/Add_Rendered_Strips/assets/140118512/55ce0aff-b609-42cc-ae3a-a9c34883c904)
I guess this is a bug?

**Comment by Craanky** [comment]
Im on Linux btw

**Comment by tin2tin** [comment]
There is no logic reason in the add-on for this to be registered twice. I also noticed this once in a while, so it's some glitch in Blender. 

If it bothers you, hit F3 and type in Reload Scripts:
![image](https://github.com/tin2tin/Add_Rendered_Strips/assets/1322593/53c7f7d6-6379-47bf-bb9b-fbf417766bf4)
